# Generated by Django 3.1.2 on 2020-11-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201105_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='', upload_to='user_images/'),
        ),
    ]
