# Generated by Django 3.1.2 on 2020-11-06 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='user.png', upload_to='user_images/'),
        ),
        migrations.CreateModel(
            name='WOMEN_CLOTH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('women_cloth_category', models.CharField(choices=[('top', 'top'), ('pants', 'pants'), ('Saree', 'saree'), ('punjabi', 'punjabi'), ('western', 'western')], default='', max_length=100)),
                ('women_cloth_name', models.CharField(max_length=100)),
                ('women_cloth_price', models.CharField(max_length=100)),
                ('women_cloth_brand', models.CharField(max_length=100)),
                ('women_cloth_desc', models.TextField()),
                ('women_cloth_image', models.ImageField(default='', upload_to='cloths/')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
