# Generated by Django 3.1.2 on 2020-11-19 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_men_cloth'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOMEN_ACCESSORIES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('women_acc_category', models.CharField(choices=[('sunglasses', 'sunglasses'), ('necklace', 'necklace'), ('watch', 'watch'), ('tie', 'tie'), ('purse', 'purse'), ('ring', 'ring'), ('hair_band', 'hair_band'), ('cap', 'cap')], default='', max_length=100)),
                ('women_acc_name', models.CharField(max_length=100)),
                ('women_acc_price', models.CharField(max_length=100)),
                ('women_acc_brand', models.CharField(max_length=100)),
                ('women_acc_desc', models.TextField()),
                ('women_acc_image', models.ImageField(default='', upload_to='women_acc/')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
