# Generated by Django 3.1.2 on 2020-11-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_women_accessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEN_ACCESSORIES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_acc_category', models.CharField(choices=[('m_sunglasses', 'm_sunglasses'), ('suspenders', 'suspenders'), ('m_watch', 'm_watch'), ('m_tie', 'm_tie'), ('m_purse', 'm_purse'), ('belt', 'belt'), ('socks', 'socks'), ('m_cap', 'm_cap')], default='', max_length=100)),
                ('men_acc_name', models.CharField(max_length=100)),
                ('men_acc_price', models.CharField(max_length=100)),
                ('men_acc_brand', models.CharField(max_length=100)),
                ('men_acc_desc', models.TextField()),
                ('men_acc_image', models.ImageField(default='', upload_to='men_acc/')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
