# Generated by Django 3.1.2 on 2020-11-23 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_men_accessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOMEN_FOOTWEAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('women_footwear_category', models.CharField(choices=[('wedges', 'wedges'), ('ballerinas', 'ballerinas'), ('canvas_shoes', 'canvas_shoes'), ('wellington_boots', 'wellington_boots'), ('flip_flop', 'flip_flop'), ('sandals', 'sandals'), ('sport_shoes', 'sport_shoes'), ('heels', 'heels')], default='', max_length=100)),
                ('women_footwear_name', models.CharField(max_length=100)),
                ('women_footwear_price', models.CharField(max_length=100)),
                ('women_footwear_brand', models.CharField(max_length=100)),
                ('women_footwear_desc', models.TextField()),
                ('women_footwear_image', models.ImageField(default='', upload_to='women_footwear/')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
