# Generated by Django 3.1.2 on 2020-11-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_men_footwear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men_footwear',
            name='men_footwear_category',
            field=models.CharField(choices=[('m_sandals', 'm_sandals'), ('m_flipflop', 'm_flipflop'), ('m_canvas_shoes', 'm_canvas_shoes'), ('brogues', 'brogues'), ('oxford', 'oxford'), ('loafers', 'loafers'), ('m_sport_shoes', 'm_sport_shoes'), ('leather', 'leather')], default='', max_length=100),
        ),
    ]
