# Generated by Django 3.1.2 on 2020-11-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20201124_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='women_cloth',
            name='women_cloth_stock',
            field=models.CharField(default='Available', max_length=100),
        ),
    ]
