# Generated by Django 3.1.2 on 2020-11-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20201128_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men_accessories',
            name='men_acc_image1',
            field=models.ImageField(default='https://www.google.com/url?sa=i&url=http%3A%2F%2Fwww.memeyacht.com%2FNews%2Fnewsdetails%2F16%2FTest_news_for_no_images&psig=AOvVaw0zsymYf4axk1v8BWO4O9P1&ust=1606631679319000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPDl6MfPpO0CFQAAAAAdAAAAABAD', upload_to='men_acc/'),
        ),
        migrations.AlterField(
            model_name='men_accessories',
            name='men_acc_image2',
            field=models.ImageField(default='https://www.google.com/url?sa=i&url=http%3A%2F%2Fwww.memeyacht.com%2FNews%2Fnewsdetails%2F16%2FTest_news_for_no_images&psig=AOvVaw0zsymYf4axk1v8BWO4O9P1&ust=1606631679319000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPDl6MfPpO0CFQAAAAAdAAAAABAD', upload_to='men_acc/'),
        ),
        migrations.AlterField(
            model_name='men_accessories',
            name='men_acc_image3',
            field=models.ImageField(default='https://www.google.com/url?sa=i&url=http%3A%2F%2Fwww.memeyacht.com%2FNews%2Fnewsdetails%2F16%2FTest_news_for_no_images&psig=AOvVaw0zsymYf4axk1v8BWO4O9P1&ust=1606631679319000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPDl6MfPpO0CFQAAAAAdAAAAABAD', upload_to='men_acc/'),
        ),
    ]
