# Generated by Django 3.1.2 on 2020-11-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_women_cloth_women_cloth_proid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women_cloth',
            name='women_cloth_proID',
            field=models.CharField(default='WC000', max_length=100),
        ),
    ]
