# Generated by Django 3.1.2 on 2020-11-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='men_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.men_accessories'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='men_cloth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.men_cloth'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='men_footwear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.men_footwear'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='women_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.women_accessories'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='women_cloth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.women_cloth'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='women_footwear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.women_footwear'),
        ),
    ]
