# Generated by Django 3.1.2 on 2020-11-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='men_accessories',
            name='men_acc_proID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='men_cloth',
            name='men_cloth_proID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='men_footwear',
            name='men_footwear_proID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='women_accessories',
            name='women_acc_proID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='women_footwear',
            name='women_footwear_proID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='women_cloth',
            name='women_cloth_proID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
