# Generated by Django 3.1.1 on 2020-12-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_auto_20201130_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='women_cloth',
            name='women_cloth_size',
            field=models.CharField(default='', max_length=100),
        ),
    ]
