# Generated by Django 3.1.1 on 2020-12-01 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_auto_20201201_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='men_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.men_accessories'),
        ),
        migrations.AddField(
            model_name='cart',
            name='men_cloth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.men_cloth'),
        ),
        migrations.AddField(
            model_name='cart',
            name='men_footwear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.men_footwear'),
        ),
        migrations.AddField(
            model_name='cart',
            name='women_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.women_accessories'),
        ),
        migrations.AddField(
            model_name='cart',
            name='women_footwear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.women_footwear'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='men_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.men_accessories'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='men_cloth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.men_cloth'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='men_footwear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.men_footwear'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='women_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.women_accessories'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='women_footwear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.women_footwear'),
        ),
    ]
