# Generated by Django 3.1.1 on 2020-12-01 09:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_auto_20201201_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='men_acc',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='men_cloth',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='men_footwear',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='women_acc',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='women_footwear',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='men_acc',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='men_cloth',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='men_footwear',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='women_acc',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='women_footwear',
        ),
        migrations.CreateModel(
            name='WA_WISHLIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('women_acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.women_accessories')),
            ],
        ),
        migrations.CreateModel(
            name='WA_CART',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('total_price', models.IntegerField()),
                ('total_qty', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('women_acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.women_accessories')),
            ],
        ),
    ]
