# Generated by Django 3.1.1 on 2020-12-01 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_auto_20201201_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wa_wishlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wa_wishlist',
            name='women_acc',
        ),
        migrations.AddField(
            model_name='cart',
            name='men_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.men_accessories'),
        ),
        migrations.AddField(
            model_name='cart',
            name='men_cloth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.men_cloth'),
        ),
        migrations.AddField(
            model_name='cart',
            name='men_footwear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.men_footwear'),
        ),
        migrations.AddField(
            model_name='cart',
            name='women_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.women_accessories'),
        ),
        migrations.AddField(
            model_name='cart',
            name='women_footwear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.women_footwear'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='men_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.men_accessories'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='men_cloth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.men_cloth'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='men_footwear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.men_footwear'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='women_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.women_accessories'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='women_footwear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.women_footwear'),
        ),
        migrations.DeleteModel(
            name='WA_CART',
        ),
        migrations.DeleteModel(
            name='WA_WISHLIST',
        ),
    ]
