# Generated by Django 3.1.1 on 2020-12-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='men_accessories',
            name='men_acc_size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='men_cloth',
            name='men_cloth_size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='men_footwear',
            name='men_footwear_size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='women_accessories',
            name='women_acc_size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='women_footwear',
            name='women_footwear_size',
            field=models.CharField(default='', max_length=100),
        ),
    ]
