# Generated by Django 3.1.2 on 2020-12-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_auto_20201201_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHECKOUT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=20)),
                ('e_mail', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('m_obile', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('add1', models.TextField()),
                ('add2', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('india', 'india')], default='', max_length=20)),
                ('state', models.CharField(choices=[('andhra', 'andhra'), ('arunachal', 'arunachal'), ('assam', 'assam'), ('bihar', 'bihar'), ('goa', 'goa'), ('gujrat', 'gujrat'), ('haryana', 'haryana'), ('himachal', 'himachal'), ('jharkhand', 'jharkhand'), ('karnataka', 'karnataka'), ('kerala', 'kerala'), ('mp', 'mp'), ('mh', 'mh'), ('manipur', 'manipur'), ('meghalaya', 'meghalaya'), ('mizoram', 'mizoram'), ('nagaland', 'nagaland'), ('odisha', 'odisha'), ('punjab', 'punjab'), ('rj', 'rj'), ('sikkim', 'sikkim'), ('tn', 'tn'), ('telangana', 'telangana'), ('tripura', 'tripura'), ('up', 'up'), ('uk', 'uk'), ('wb', 'wb')], default='', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='women_cloth',
            name='women_cloth_proID',
            field=models.CharField(max_length=100),
        ),
    ]
