# Generated by Django 3.1.2 on 2020-12-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CHECKOUT',
        ),
        migrations.AddField(
            model_name='transaction',
            name='add1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='add2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='country',
            field=models.CharField(choices=[('india', 'india')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='e_mail',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fax',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='m_obile',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='post_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('andhra', 'andhra'), ('arunachal', 'arunachal'), ('assam', 'assam'), ('bihar', 'bihar'), ('goa', 'goa'), ('gujrat', 'gujrat'), ('haryana', 'haryana'), ('himachal', 'himachal'), ('jharkhand', 'jharkhand'), ('karnataka', 'karnataka'), ('kerala', 'kerala'), ('mp', 'mp'), ('mh', 'mh'), ('manipur', 'manipur'), ('meghalaya', 'meghalaya'), ('mizoram', 'mizoram'), ('nagaland', 'nagaland'), ('odisha', 'odisha'), ('punjab', 'punjab'), ('rj', 'rj'), ('sikkim', 'sikkim'), ('tn', 'tn'), ('telangana', 'telangana'), ('tripura', 'tripura'), ('up', 'up'), ('uk', 'uk'), ('wb', 'wb')], default='', max_length=20),
        ),
    ]
