# Generated by Django 3.1.2 on 2020-12-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_auto_20201204_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHECKOUT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('e_mail', models.CharField(max_length=20)),
                ('m_obile', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('add1', models.CharField(max_length=50)),
                ('add2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('india', 'india')], default='', max_length=20)),
                ('state', models.CharField(choices=[('andhra', 'andhra'), ('arunachal', 'arunachal'), ('assam', 'assam'), ('bihar', 'bihar'), ('goa', 'goa'), ('gujrat', 'gujrat'), ('haryana', 'haryana'), ('himachal', 'himachal'), ('jharkhand', 'jharkhand'), ('karnataka', 'karnataka'), ('kerala', 'kerala'), ('mp', 'mp'), ('mh', 'mh'), ('manipur', 'manipur'), ('meghalaya', 'meghalaya'), ('mizoram', 'mizoram'), ('nagaland', 'nagaland'), ('odisha', 'odisha'), ('punjab', 'punjab'), ('rj', 'rj'), ('sikkim', 'sikkim'), ('tn', 'tn'), ('telangana', 'telangana'), ('tripura', 'tripura'), ('up', 'up'), ('uk', 'uk'), ('wb', 'wb')], default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='add1',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='add2',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='city',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='country',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='e_mail',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='m_obile',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='state',
        ),
    ]
