# Generated by Django 3.1.2 on 2020-12-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_auto_20201204_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
