# Generated by Django 3.1.2 on 2020-12-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_transaction_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='men_cloth',
            name='men_cloth_image1',
            field=models.ImageField(default='plus.png', upload_to='men_cloths/'),
        ),
        migrations.AddField(
            model_name='men_cloth',
            name='men_cloth_image2',
            field=models.ImageField(default='plus.png', upload_to='men_cloths/'),
        ),
        migrations.AddField(
            model_name='men_cloth',
            name='men_cloth_image3',
            field=models.ImageField(default='plus.png', upload_to='men_cloths/'),
        ),
        migrations.AddField(
            model_name='men_footwear',
            name='men_footwear_image1',
            field=models.ImageField(default='plus.png', upload_to='men_footwear/'),
        ),
        migrations.AddField(
            model_name='men_footwear',
            name='men_footwear_image2',
            field=models.ImageField(default='plus.png', upload_to='men_footwear/'),
        ),
        migrations.AddField(
            model_name='men_footwear',
            name='men_footwear_image3',
            field=models.ImageField(default='plus.png', upload_to='men_footwear/'),
        ),
        migrations.AddField(
            model_name='women_accessories',
            name='women_acc_image1',
            field=models.ImageField(default='plus.png', upload_to='women_acc/'),
        ),
        migrations.AddField(
            model_name='women_accessories',
            name='women_acc_image2',
            field=models.ImageField(default='plus.png', upload_to='women_acc/'),
        ),
        migrations.AddField(
            model_name='women_accessories',
            name='women_acc_image3',
            field=models.ImageField(default='plus.png', upload_to='women_acc/'),
        ),
        migrations.AddField(
            model_name='women_cloth',
            name='women_cloth_image1',
            field=models.ImageField(default='plus.png', upload_to='women_cloths/'),
        ),
        migrations.AddField(
            model_name='women_cloth',
            name='women_cloth_image2',
            field=models.ImageField(default='plus.png', upload_to='women_cloths/'),
        ),
        migrations.AddField(
            model_name='women_cloth',
            name='women_cloth_image3',
            field=models.ImageField(default='plus.png', upload_to='women_cloths/'),
        ),
        migrations.AddField(
            model_name='women_footwear',
            name='women_footwear_image1',
            field=models.ImageField(default='plus.png', upload_to='women_footwear/'),
        ),
        migrations.AddField(
            model_name='women_footwear',
            name='women_footwear_image2',
            field=models.ImageField(default='plus.png', upload_to='women_footwear/'),
        ),
        migrations.AddField(
            model_name='women_footwear',
            name='women_footwear_image3',
            field=models.ImageField(default='plus.png', upload_to='women_footwear/'),
        ),
    ]
