# Generated by Django 3.1.2 on 2020-12-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_auto_20201208_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men_cloth',
            name='men_cloth_proID',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='women_accessories',
            name='women_acc_proID',
            field=models.CharField(max_length=10),
        ),
    ]
