# Generated by Django 3.1.2 on 2020-12-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_auto_20201208_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women_cloth',
            name='women_cloth_proID',
            field=models.CharField(max_length=10),
        ),
    ]
