# Generated by Django 3.1.2 on 2020-12-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_auto_20201209_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women_footwear',
            name='women_footwear_proID',
            field=models.CharField(max_length=100),
        ),
    ]
